### PR TITLE
update classrooms struct to api specification

### PR DESCRIPTION
**Pull request by vibhubehl**
Ticket: https://seng499-b01-company2.atlassian.net/jira/software/projects/C2/boards/1?selectedIssue=C2-47

This PR introduces the following changes:

- Adds Token based authentication will access to All classrooms endpoints
- Adds role-based access using jwt to admins for PUT, POST and DELETE. 
- Updates the classroom's struct to meet the API specification.

### CODE REVIEW

**Review by jakecomp — CHANGES_REQUESTED** [review]
Hey Vibhu, I think all you need to do to pass the tests is just update the classroom_test file so that it no longer expects the equipment field.  

image

**Review by AnthonyRodway — COMMENTED** [review]
Looks good once the tests are passing 👍

**Review by jberryman566 — APPROVED** [review]

**Comment by vibhubehl** [comment]
> Hey Vibhu, I think all you need to do to pass the tests is just update the classroom_test file so that it no longer expects the equipment field.
> 
> image

@jakecomp done. I have fixed the tests.

**Review by jberryman566 — APPROVED** [review]

**Review by jakecomp — APPROVED** [review]

**Comment by jakecomp** [comment]
Good to go!

**Pull request merged**
