### PR TITLE
CRUD Courses

### PR DESCRIPTION
**Pull request by vibhubehl**
Ticket: https://seng499-b01-company2.atlassian.net/browse/C2-8
This PR adds CRUD operations for courses. The following endpoints are added:

1. GET /courses/{courseShortHand}
2. GET /courses
3. POST /courses
4. PUT /courses/{courseShortHand}
5. DELETE /courses/{courseShortHand}

The endpoints check whether course shorthand is in the form of ABC101/ ABC101B.
For GET /courses/{courseShortHand}, PUT /courses/{courseShortHand} and DELETE /courses/{courseShortHand} throws an error if the given course shorthand is already not in the courses DB.

### CODE REVIEW

**Review by jberryman566 — APPROVED** [review]
LGTM! Well done!

**Comment by NishchintDhawan** [comment]
LGTM!

**Review by jakecomp — CHANGES_REQUESTED** [review]
I think we should still keep our .gitignore file. Was there any reason to delete it?

**Comment by vibhubehl** [comment]
> I think we should still keep our .gitignore file. Was there any reason to delete it?
@jakecomp I thought we were not supposed to push .gitignore. Let me just add it back.

**Comment by vibhubehl** [comment]
> I think we should still keep our .gitignore file. Was there any reason to delete it?

@jakecomp Done

**Comment by jakecomp** [comment]
I don't think it hurts to have it on the repo. Other than that everything looks great!

**Review by jakecomp — APPROVED** [review]

**Pull request merged**
